image: openjdk:17-alpine

pipelines:
   default:
      - step:
         caches:
          - maven
         script:
          - /bin/sh mvnw clean install
         artifacts:
          - target/*.zip
      - step:
         deployment: Production
         script:
          - pipe: atlassian/ftp-deploy:0.3.6
            variables:
              USER: $FTP_USER
              PASSWORD: $FTP_PASSWORD
              SERVER: $FTP_HOST
              REMOTE_PATH: $FTP_REMOTE_PATH
              LOCAL_PATH: 'target/'